# Default values for userservice.
# This is a YAML-formatted file.
# Declare variables to be substituted into your templates.

replicaCount: 2

image:
  repository: userservice
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: userservice.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: userservice-tls
      hosts:
        - userservice.yourdomain.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Spring Boot configuration
config:
  spring:
    profiles:
      active: prod
  server:
    port: 8081

# Environment variables (override with your actual values)
env:
  # Database
  DB_URL: "jdbc:mysql://mysql:3306/userservice"
  DB_USERNAME: "userservice"
  DB_PASSWORD: ""  # Set via secret
  DB_DRIVER: "com.mysql.cj.jdbc.Driver"
  
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SERVICE_NAME: "user-svc"
  
  # Auth0 (set via secret)
  AUTH0_ISSUER_URI: ""
  AUTH0_AUDIENCE: ""
  AUTH0_CLIENT_ID: ""
  
  # TossPay (set via secret)
  TOSSPAY_SECRET_KEY: ""
  TOSSPAY_CLIENT_ID: ""
  TOSSPAY_WEBHOOK_SECRET: ""
  
  # Eureka
  EUREKA_SERVER_URL: "http://eureka:8761/eureka/"
  
  # Build
  BUILD_VERSION: "1.0.0"
  DDL_AUTO: "update"

# External secrets (create these in your cluster)
secrets:
  database:
    enabled: true
    name: userservice-db-secret
  auth0:
    enabled: true
    name: userservice-auth0-secret
  tosspay:
    enabled: true
    name: userservice-tosspay-secret

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Monitoring
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  interval: 30s

# Dependencies
dependencies:
  mysql:
    enabled: false  # Set to true if you want to deploy MySQL as part of this chart
  redis:
    enabled: false  # Set to true if you want to deploy Redis as part of this chart