{{- if .Values.filebeat.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customApiSvc.fullname" . }}-filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customApiSvc.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "customApiSvc.fullname" . }}-filebeat
  labels:
    {{- include "customApiSvc.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "customApiSvc.fullname" . }}-filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "customApiSvc.fullname" . }}-filebeat
subjects:
- kind: ServiceAccount
  name: {{ include "customApiSvc.fullname" . }}-filebeat
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "customApiSvc.fullname" . }}-filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customApiSvc.labels" . | nindent 4 }}
    app.kubernetes.io/component: filebeat
spec:
  selector:
    matchLabels:
      {{- include "customApiSvc.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: filebeat
  template:
    metadata:
      labels:
        {{- include "customApiSvc.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: filebeat
    spec:
      serviceAccountName: {{ include "customApiSvc.fullname" . }}-filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: "{{ .Values.filebeat.image.repository }}:{{ .Values.filebeat.image.tag }}"
        imagePullPolicy: {{ .Values.filebeat.image.pullPolicy }}
        args: [ "-c", "/etc/filebeat.yml", "-e" ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          {{- toYaml .Values.filebeat.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "customApiSvc.fullname" . }}-filebeat-config
      - name: varlibdockercontainers
        hostPath: { path: /var/lib/docker/containers }
      - name: varlog
        hostPath: { path: /var/log }
{{- end }}